# Generated by Django 3.2.5 on 2021-08-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('text_01', models.CharField(max_length=100)),
                ('text_02', models.CharField(max_length=100)),
                ('text_03', models.CharField(max_length=100)),
                ('text_04', models.CharField(max_length=100)),
                ('text_05', models.CharField(max_length=100)),
                ('text_06', models.CharField(max_length=100)),
                ('text_07', models.CharField(max_length=100)),
                ('text_08', models.CharField(max_length=100)),
                ('text_09', models.CharField(max_length=100)),
                ('text_10', models.CharField(max_length=100)),
            ],
        ),
    ]
